name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: '镜像标签'
        required: true
        default: 'latest'
        type: string
      build-platforms:
        description: '构建平台'
        required: false
        default: 'linux/amd64'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/node-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image-tag }}
          platforms: ${{ inputs.build-platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
